"""G1 kick-ball recipe."""
from __future__ import annotations

from ._common import (
    SOCCER_AUTO_EXPERIMENTS,
    SOCCER_CONSTRAINTS,
    SOCCER_ENV_ASSUMPTIONS,
    SOCCER_FAILURES,
    SOCCER_HOW_TRIGGERS,
    SOCCER_MEMORY_QUERIES,
    SOCCER_PRIORS,
    SOCCER_PROHIBITED,
    SOCCER_SCENE_OBJECTS,
    SOCCER_SCENE_UNCERTAINTY,
)
from ._types import SubtaskRecipe, TaskRecipe

G1_KICK_BALL_RECIPE = TaskRecipe(
    task_id="g1_kick_ball",
    title="Unitree G1 踢足球任务",
    natural_language_goal="让 G1 踢足球",
    normalized_goal="Unitree G1 detects a ball, approaches it, stabilizes posture, kicks it toward a target, and recovers balance.",
    task_type="physical_skill",
    task_family="humanoid_locomotion_object_interaction",
    domain="control_locomotion",
    difficulty="high",
    expected_outcome=[
        "识别足球位置",
        "接近足球",
        "保持身体稳定",
        "完成踢球动作",
        "踢球后恢复平衡",
    ],
    success_criteria=[
        {"id": "ball_detected", "description": "足球被正确识别并定位", "metric": "perception_confidence", "threshold": ">=0.75"},
        {"id": "approach_success", "description": "G1 到达可踢球范围", "metric": "distance_to_ball", "threshold": "<=0.35m"},
        {"id": "kick_contact", "description": "脚部与足球发生有效接触", "metric": "contact_event", "threshold": "true"},
        {"id": "ball_motion", "description": "足球沿目标方向移动", "metric": "ball_displacement", "threshold": ">=0.5m"},
        {"id": "balance_recovery", "description": "踢球后 3 秒内未摔倒", "metric": "fall_event", "threshold": "false"},
    ],
    tags=["humanoid", "locomotion", "soccer", "manipulation_by_leg", "safety_critical"],
    embodiment_type="humanoid",
    relevant_body_parts=["torso", "left_leg", "right_leg", "feet", "head_camera", "imu"],
    required_capabilities=[
        "visual_ball_detection",
        "whole_body_balance",
        "bipedal_locomotion",
        "foot_trajectory_control",
        "contact_aware_recovery",
    ],
    assumptions=[
        "G1 当前处于可站立状态",
        "场地允许低速踢球测试",
        "足球尺寸和颜色可被视觉系统识别",
    ],
    subtasks=[
        SubtaskRecipe(
            id="perceive_ball",
            name="识别和定位足球",
            phase="perception",
            description="使用头部相机或外部视觉系统识别足球位置",
            inputs=["rgb_image", "depth_image", "camera_pose"],
            outputs=["ball_pose", "perception_confidence"],
            required_capabilities=["visual_ball_detection"],
            success_criteria=["perception_confidence >= 0.75"],
            likely_failures=["ball_not_detected", "ball_pose_drift", "false_positive_object"],
        ),
        SubtaskRecipe(
            id="plan_approach",
            name="规划接近路径",
            phase="planning",
            description="规划从当前位置到足球可踢位置的低速路径",
            inputs=["robot_pose", "ball_pose", "scene_obstacles"],
            outputs=["approach_path", "kick_stance_pose"],
            required_capabilities=["local_navigation", "collision_check"],
            success_criteria=["path_collision_free == true", "kick_stance_pose_reachable == true"],
            likely_failures=["path_blocked", "stance_unreachable", "collision_risk"],
        ),
        SubtaskRecipe(
            id="approach_ball",
            name="执行接近动作",
            phase="locomotion",
            description="低速走到足球附近，保持平衡",
            inputs=["approach_path", "robot_state"],
            outputs=["final_stance_pose", "balance_margin"],
            required_capabilities=["bipedal_locomotion", "balance_control"],
            success_criteria=["distance_to_ball <= 0.35m", "balance_margin >= 0.2"],
            likely_failures=["foot_slip", "balance_loss", "odometry_drift"],
        ),
        SubtaskRecipe(
            id="align_for_kick",
            name="调整踢球姿态",
            phase="whole_body_control",
            description="调整支撑脚、身体朝向和踢球腿位置",
            inputs=["final_stance_pose", "ball_pose", "target_zone_pose"],
            outputs=["support_foot_pose", "kicking_foot_prepose"],
            required_capabilities=["whole_body_balance", "foot_pose_control"],
            success_criteria=["support_polygon_stable == true", "kicking_leg_reachable == true"],
            likely_failures=["unstable_support", "leg_reach_limit", "self_collision_risk"],
        ),
        SubtaskRecipe(
            id="execute_kick",
            name="执行踢球动作",
            phase="control",
            description="执行低速、受限幅的踢球轨迹",
            inputs=["kicking_foot_prepose", "ball_pose", "target_direction"],
            outputs=["foot_trajectory", "contact_event", "ball_velocity"],
            required_capabilities=["foot_trajectory_control", "contact_timing", "torque_limit_monitoring"],
            success_criteria=["contact_event == true", "ball_displacement >= 0.5m", "torque_limit_violation == false"],
            likely_failures=["missed_ball", "weak_contact", "excessive_contact_force", "torque_limit_violation"],
        ),
        SubtaskRecipe(
            id="recover_balance",
            name="踢球后恢复平衡",
            phase="recovery",
            description="踢球后收腿、恢复双脚支撑并保持稳定",
            inputs=["post_kick_robot_state", "imu", "joint_states"],
            outputs=["stable_standing_state"],
            required_capabilities=["balance_recovery", "fall_detection"],
            success_criteria=["fall_event == false", "stable_standing_duration >= 3s"],
            likely_failures=["fall_risk", "unstable_recovery", "joint_overheat"],
        ),
    ],
    required_scene_objects=SOCCER_SCENE_OBJECTS,
    environmental_assumptions=SOCCER_ENV_ASSUMPTIONS,
    scene_uncertainty=SOCCER_SCENE_UNCERTAINTY,
    additional_failures=SOCCER_FAILURES,
    additional_constraints=SOCCER_CONSTRAINTS,
    engineering_priors=SOCCER_PRIORS,
    memory_queries=SOCCER_MEMORY_QUERIES,
    how_triggers=SOCCER_HOW_TRIGGERS,
    auto_experiments=SOCCER_AUTO_EXPERIMENTS,
    prohibited_experiments=SOCCER_PROHIBITED,
    cognitive_wiki_terms=[
        "humanoid kick ball",
        "biped kicking balance recovery",
        "Unitree G1 locomotion control",
        "foot trajectory contact ball",
    ],
    cognitive_wiki_cards=[
        ("humanoid_balance_recovery", 0.83),
        ("low_speed_contact_safety", 0.91),
    ],
    valid_robots=["unitree_g1"],
)
