"""G1 press-button recipe."""
from __future__ import annotations

from ._types import SubtaskRecipe, TaskRecipe

BUTTON_SCENE_OBJECTS = [
    ("button", "push_button", {"diameter": "0.05m", "force_limit": "5N"}),
]

G1_PRESS_BUTTON_RECIPE = TaskRecipe(
    task_id="g1_press_button",
    title="G1 按按钮任务",
    natural_language_goal="让 G1 按按钮",
    normalized_goal="Unitree G1 detects a push button, approaches it, aligns its hand, and presses it with a force-limited motion.",
    task_type="manipulation",
    task_family="humanoid_manipulation_force_limited",
    domain="control_manipulation",
    difficulty="medium",
    expected_outcome=[
        "识别按钮位置",
        "接近按钮",
        "调整手部姿态",
        "完成力控按压",
        "保持平衡",
    ],
    success_criteria=[
        {"id": "button_detected", "description": "按钮被正确识别并定位", "metric": "perception_confidence", "threshold": ">=0.75"},
        {"id": "press_contact", "description": "手指与按钮发生有效接触", "metric": "contact_event", "threshold": "true"},
        {"id": "force_within_limit", "description": "按压力不超过 5N", "metric": "contact_force", "threshold": "<=5N"},
    ],
    tags=["humanoid", "manipulation", "force_limited", "safety_critical"],
    embodiment_type="humanoid",
    relevant_body_parts=["torso", "arm", "hand", "head_camera", "imu"],
    required_capabilities=[
        "visual_button_detection",
        "arm_motion_planning",
        "force_control",
        "whole_body_balance",
    ],
    assumptions=[
        "G1 当前处于可站立状态",
        "按钮高度在可达范围内",
        "按钮可被视觉系统识别",
    ],
    subtasks=[
        SubtaskRecipe(
            id="perceive_button",
            name="识别和定位按钮",
            phase="perception",
            description="使用头部相机识别按钮位置",
            inputs=["rgb_image", "depth_image", "camera_pose"],
            outputs=["button_pose", "perception_confidence"],
            required_capabilities=["visual_button_detection"],
            success_criteria=["perception_confidence >= 0.75"],
            likely_failures=["button_not_detected", "button_pose_drift", "false_positive_object"],
        ),
        SubtaskRecipe(
            id="plan_approach",
            name="规划接近路径",
            phase="planning",
            description="规划从当前位置到按钮可达范围的站立位置",
            inputs=["robot_pose", "button_pose", "scene_obstacles"],
            outputs=["approach_path", "manipulation_stance"],
            required_capabilities=["local_navigation", "collision_check"],
            success_criteria=["path_collision_free == true", "manipulation_stance_reachable == true"],
            likely_failures=["path_blocked", "stance_unreachable", "collision_risk"],
        ),
        SubtaskRecipe(
            id="approach_button",
            name="执行接近动作",
            phase="locomotion",
            description="低速走到按钮附近，保持平衡",
            inputs=["approach_path", "robot_state"],
            outputs=["final_stance_pose", "balance_margin"],
            required_capabilities=["bipedal_locomotion", "balance_control"],
            success_criteria=["distance_to_button <= 0.6m", "balance_margin >= 0.2"],
            likely_failures=["foot_slip", "balance_loss", "odometry_drift"],
        ),
        SubtaskRecipe(
            id="align_hand",
            name="调整手部按压姿态",
            phase="manipulation",
            description="调整手臂、手掌与按钮的相对位姿",
            inputs=["final_stance_pose", "button_pose"],
            outputs=["hand_prepose", "approach_direction"],
            required_capabilities=["arm_motion_planning", "hand_pose_control"],
            success_criteria=["hand_reachable == true", "approach_direction_safe == true"],
            likely_failures=["hand_unreachable", "self_collision_risk", "unstable_base"],
        ),
        SubtaskRecipe(
            id="execute_press",
            name="执行力控按压",
            phase="control",
            description="以受限力完成按压动作",
            inputs=["hand_prepose", "button_pose"],
            outputs=["contact_event", "contact_force"],
            required_capabilities=["force_control", "contact_timing"],
            success_criteria=["contact_event == true", "contact_force <= 5N"],
            likely_failures=["missed_button", "excessive_force", "button_stuck"],
        ),
        SubtaskRecipe(
            id="recover_balance",
            name="按压后恢复平衡",
            phase="recovery",
            description="按压后收手、恢复双脚支撑并保持稳定",
            inputs=["post_press_robot_state", "imu", "joint_states"],
            outputs=["stable_standing_state"],
            required_capabilities=["balance_recovery", "fall_detection"],
            success_criteria=["fall_event == false", "stable_standing_duration >= 3s"],
            likely_failures=["fall_risk", "unstable_recovery", "joint_overheat"],
        ),
    ],
    required_scene_objects=BUTTON_SCENE_OBJECTS,
    environmental_assumptions=["地面平整", "按钮附近无易碎物", "没有人类站在按钮前方"],
    scene_uncertainty=[("button_pose_uncertainty", "按钮位姿估计存在视觉误差", "±2cm")],
    additional_failures=[
        {
            "id": "button_not_detected",
            "category": "perception_failure",
            "applies_to": ["perceive_button"],
            "description": "视觉系统无法检测到按钮",
            "observable_signals": ["perception_confidence < 0.5", "button_pose is null"],
            "likely_causes": ["光照不足", "按钮被遮挡", "颜色与背景相近"],
            "severity": "S1",
            "recovery": ["调整头部视角", "请求多视角观察"],
            "how_trigger": {"enabled": True, "query_hint": "button detection failure visual perception"},
            "memory_write": {"enabled": True, "event_type": "perception_failure"},
        },
        {
            "id": "excessive_force",
            "category": "safety_failure",
            "applies_to": ["execute_press"],
            "description": "按压力超过按钮安全阈值",
            "observable_signals": ["contact_force > 5N", "button_deformation"],
            "likely_causes": ["力控参数过大", "手臂惯性", "按钮阻力异常"],
            "severity": "S3",
            "recovery": ["立即停止按压", "降低力控上限", "重新对齐"],
            "how_trigger": {"enabled": True, "expected_strategy": "SAFETY", "query_hint": "excessive contact force humanoid manipulation"},
            "memory_write": {"enabled": True, "event_type": "safety_failure"},
        },
    ],
    additional_constraints=[
        {
            "id": "force_limit_5n",
            "type": "hardware_safety",
            "description": "按压力不得超过 5N",
            "applies_to": ["execute_press"],
            "check": {"method": "telemetry", "expression": "contact_force <= 5N"},
            "violation_action": "STOP_AND_RECOVER",
            "how_strategy": "SAFETY",
        },
    ],
    engineering_priors=[
        {"id": "force_limit_first", "type": "safety_prior", "description": "首次接触必须使用低力控上限", "applies_to": ["execute_press"], "source": "curated", "confidence": 0.9},
        {"id": "balance_while_reaching", "type": "control_prior", "description": "伸手按压时保持重心在支撑面内", "applies_to": ["align_hand", "execute_press"], "source": "cognitive_wiki", "confidence": 0.85},
    ],
    memory_queries=[
        {"id": "similar_button_tasks", "query": "G1 press button force limit balance", "intent": "retrieve_similar_episode", "top_k": 5},
    ],
    how_triggers=[
        {"id": "missed_button", "when": {"metric": "contact_event", "condition": "false"}, "query_hint": "missed button hand trajectory timing"},
        {"id": "excessive_force", "when": {"metric": "contact_force", "condition": "> 5N"}, "query_hint": "excessive contact force humanoid manipulation", "expected_strategy": "SAFETY"},
    ],
    auto_experiments=[
        {"id": "approach_distance_sweep", "description": "测试不同接近距离", "variables": ["distance_to_button"], "values": ["0.5m", "0.6m", "0.7m"], "safety_gate": True},
    ],
    prohibited_experiments=["disable_force_limit", "press_toward_human"],
    cognitive_wiki_terms=["humanoid force limited manipulation", "biped balance reaching"],
    cognitive_wiki_cards=[("humanoid_balance_reaching", 0.82)],
    valid_robots=["unitree_g1"],
)
