"""Go2 inspect-meter recipe."""
from __future__ import annotations

from ._types import SubtaskRecipe, TaskRecipe

GO2_INSPECT_METER_RECIPE = TaskRecipe(
    task_id="go2_inspect_meter",
    title="Go2 巡检仪表任务",
    natural_language_goal="让 Go2 巡检仪表",
    normalized_goal="Unitree Go2 navigates to a meter, selects a viewpoint, reads the display, and reports the value.",
    task_type="inspection",
    task_family="quadruped_navigation_inspection",
    domain="perception_navigation",
    difficulty="medium",
    expected_outcome=[
        "到达仪表附近",
        "选择合适观测视角",
        "读取仪表数值",
        "上报读数",
    ],
    success_criteria=[
        {"id": "meter_in_view", "description": "仪表完整出现在相机视野", "metric": "meter_in_view", "threshold": "true"},
        {"id": "reading_confidence", "description": "OCR 读数置信度足够", "metric": "ocr_confidence", "threshold": ">=0.8"},
    ],
    tags=["quadruped", "navigation", "inspection", "ocr"],
    embodiment_type="quadruped",
    relevant_body_parts=["body", "head_camera", "legs", "imu"],
    required_capabilities=[
        "autonomous_navigation",
        "viewpoint_selection",
        "ocr_reading",
        "terrain_aware_locomotion",
    ],
    assumptions=[
        "仪表位置大致已知",
        "地面允许四足通行",
        "仪表显示清晰可读",
    ],
    subtasks=[
        SubtaskRecipe(
            id="navigate_to_meter",
            name="导航到仪表附近",
            phase="navigation",
            description="规划并执行到仪表附近的安全路径",
            inputs=["map", "meter_waypoint", "terrain_map"],
            outputs=["robot_pose_near_meter", "path_traversed"],
            required_capabilities=["autonomous_navigation", "terrain_aware_locomotion"],
            success_criteria=["distance_to_meter <= 1.0m", "path_collision_free == true"],
            likely_failures=["path_blocked", "rough_terrain", "localization_drift"],
        ),
        SubtaskRecipe(
            id="select_viewpoint",
            name="选择观测视角",
            phase="planning",
            description="选择能完整看到仪表的站立位置与头部角度",
            inputs=["robot_pose_near_meter", "meter_pose", "scene_obstacles"],
            outputs=["viewpoint_pose", "head_yaw_pitch"],
            required_capabilities=["viewpoint_selection", "collision_check"],
            success_criteria=["meter_in_view == true", "viewpoint_reachable == true"],
            likely_failures=["occlusion", "viewpoint_unreachable", "glare"],
        ),
        SubtaskRecipe(
            id="capture_image",
            name="采集仪表图像",
            phase="perception",
            description="在选定视角采集高质量图像",
            inputs=["rgb_image", "camera_pose", "head_yaw_pitch"],
            outputs=["meter_image", "image_quality_score"],
            required_capabilities=["camera_control", "image_quality_check"],
            success_criteria=["image_quality_score >= 0.7"],
            likely_failures=["motion_blur", "low_light", "meter_out_of_focus"],
        ),
        SubtaskRecipe(
            id="read_meter",
            name="OCR 读取仪表",
            phase="perception",
            description="对仪表图像进行 OCR 并返回读数",
            inputs=["meter_image"],
            outputs=["meter_reading", "ocr_confidence"],
            required_capabilities=["ocr_reading"],
            success_criteria=["ocr_confidence >= 0.8"],
            likely_failures=["ocr_failure", "partial_digits", "reflection"],
        ),
        SubtaskRecipe(
            id="report_reading",
            name="上报读数",
            phase="reporting",
            description="将读数和置信度上报",
            inputs=["meter_reading", "ocr_confidence", "viewpoint_pose"],
            outputs=["inspection_report"],
            required_capabilities=["data_reporting"],
            success_criteria=["report_submitted == true"],
            likely_failures=["report_format_error", "communication_loss"],
        ),
    ],
    required_scene_objects=[("meter", "analog_or_digital_meter", {"readable_range": "0.5m-2.0m"})],
    environmental_assumptions=["地面允许四足通行", "仪表周围有安全驻足空间", "光线足以成像"],
    scene_uncertainty=[("meter_glare", "仪表表面可能存在反光", "medium")],
    additional_failures=[
        {
            "id": "ocr_failure",
            "category": "perception_failure",
            "applies_to": ["read_meter"],
            "description": "OCR 无法识别仪表读数",
            "observable_signals": ["ocr_confidence < 0.5", "meter_reading is null"],
            "likely_causes": ["图像模糊", "反光", "仪表类型未训练"],
            "severity": "S2",
            "recovery": ["调整视角", "增强光照", "切换 OCR 模型"],
            "how_trigger": {"enabled": True, "query_hint": "meter ocr failure viewpoint"},
            "memory_write": {"enabled": True, "event_type": "perception_failure"},
        },
    ],
    additional_constraints=[
        {
            "id": "keep_safe_distance",
            "type": "human_safety",
            "description": "巡检时保持与仪表的安全距离，避免碰撞",
            "applies_to": ["navigate_to_meter"],
            "check": {"method": "telemetry", "expression": "distance_to_meter >= 0.3m"},
            "violation_action": "STOP",
            "how_strategy": "SAFETY",
        },
    ],
    engineering_priors=[
        {"id": "multiple_viewpoints", "type": "validation_prior", "description": "OCR 失败时尝试多个视角", "applies_to": ["select_viewpoint", "capture_image"], "source": "rosclaw_policy", "confidence": 0.88},
    ],
    memory_queries=[
        {"id": "similar_inspection_tasks", "query": "Go2 meter inspection ocr viewpoint", "intent": "retrieve_similar_episode", "top_k": 5},
    ],
    how_triggers=[
        {"id": "ocr_low_confidence", "when": {"metric": "ocr_confidence", "condition": "< 0.8"}, "query_hint": "meter ocr failure viewpoint"},
    ],
    auto_experiments=[
        {"id": "viewpoint_distance_sweep", "description": "测试不同观测距离", "variables": ["distance_to_meter"], "values": ["0.8m", "1.0m", "1.2m"], "safety_gate": True},
    ],
    prohibited_experiments=["disable_safety_distance", "climb_to_meter"],
    cognitive_wiki_terms=["quadruped inspection viewpoint", "meter ocr robotics"],
    cognitive_wiki_cards=[("quadruped_viewpoint_selection", 0.8)],
    valid_robots=["unitree_go2"],
)
