"""UR5 pick-cup recipe."""
from __future__ import annotations

from ._types import SubtaskRecipe, TaskRecipe

UR5_PICK_CUP_RECIPE = TaskRecipe(
    task_id="ur5_pick_cup",
    title="UR5 抓杯子任务",
    natural_language_goal="让 UR5 抓杯子",
    normalized_goal="UR5 detects a cup, plans a collision-free grasp, executes the grasp, and verifies it.",
    task_type="manipulation",
    task_family="manipulator_grasping",
    domain="control_manipulation",
    difficulty="medium",
    expected_outcome=[
        "识别杯子位置",
        "规划无碰撞抓取",
        "执行抓取",
        "验证抓取成功",
    ],
    success_criteria=[
        {"id": "cup_detected", "description": "杯子被正确识别并定位", "metric": "perception_confidence", "threshold": ">=0.75"},
        {"id": "grasp_contact", "description": "夹爪与杯子发生有效接触", "metric": "grasp_contact", "threshold": "true"},
        {"id": "cup_lifted", "description": "杯子被成功提起", "metric": "cup_lift_height", "threshold": ">=0.05m"},
    ],
    tags=["manipulator", "grasping", "ur5"],
    embodiment_type="manipulator",
    relevant_body_parts=["base", "shoulder", "elbow", "wrist", "gripper", "wrist_camera"],
    required_capabilities=[
        "object_detection",
        "grasp_planning",
        "collision_avoidance",
        "gripper_control",
    ],
    assumptions=[
        "杯子位于工作空间内",
        "夹爪开合正常",
        "杯子可被夹爪夹持",
    ],
    subtasks=[
        SubtaskRecipe(
            id="detect_cup",
            name="检测杯子",
            phase="perception",
            description="使用腕部或外部相机检测杯子位姿",
            inputs=["rgb_image", "depth_image", "camera_pose"],
            outputs=["cup_pose", "perception_confidence"],
            required_capabilities=["object_detection"],
            success_criteria=["perception_confidence >= 0.75"],
            likely_failures=["cup_not_detected", "cup_pose_drift", "occlusion"],
        ),
        SubtaskRecipe(
            id="plan_grasp",
            name="规划抓取",
            phase="planning",
            description="规划无碰撞的抓取姿态与路径",
            inputs=["cup_pose", "robot_state", "scene_obstacles"],
            outputs=["grasp_pose", "approach_path"],
            required_capabilities=["grasp_planning", "collision_avoidance"],
            success_criteria=["path_collision_free == true", "grasp_pose_reachable == true"],
            likely_failures=["no_valid_grasp", "collision_risk", "pose_unreachable"],
        ),
        SubtaskRecipe(
            id="execute_grasp",
            name="执行抓取",
            phase="control",
            description="沿路径接近并闭合夹爪",
            inputs=["approach_path", "grasp_pose"],
            outputs=["gripper_state", "grasp_contact"],
            required_capabilities=["gripper_control", "arm_trajectory_control"],
            success_criteria=["grasp_contact == true"],
            likely_failures=["missed_grasp", "slip", "excessive_force"],
        ),
        SubtaskRecipe(
            id="verify_grasp",
            name="验证抓取",
            phase="verification",
            description="提起杯子并验证稳定抓持",
            inputs=["gripper_state", "force_feedback"],
            outputs=["cup_lift_height", "grasp_stable"],
            required_capabilities=["force_feedback", "lift_motion"],
            success_criteria=["cup_lift_height >= 0.05m", "grasp_stable == true"],
            likely_failures=["cup_dropped", "grasp_unstable", "lift_collision"],
        ),
    ],
    required_scene_objects=[("cup", "drinking_cup", {"diameter": "0.08m", "height": "0.12m", "movable": True})],
    environmental_assumptions=["杯子放置在工作台上", "工作台上方无遮挡", "周围无人类手臂"],
    scene_uncertainty=[("cup_pose_uncertainty", "杯子位姿估计存在视觉误差", "±1cm")],
    additional_failures=[
        {
            "id": "no_valid_grasp",
            "category": "planning_failure",
            "applies_to": ["plan_grasp"],
            "description": "找不到无碰撞的可行抓取",
            "observable_signals": ["valid_grasp_count == 0", "grasp_pose is null"],
            "likely_causes": ["杯子位置超出可达空间", "周围障碍物过多", "夹爪开合不足"],
            "severity": "S2",
            "recovery": ["调整杯子位置", "清理障碍物", "更换夹爪配置"],
            "how_trigger": {"enabled": True, "query_hint": "no valid grasp manipulator collision"},
            "memory_write": {"enabled": True, "event_type": "planning_failure"},
        },
    ],
    additional_constraints=[
        {
            "id": "workspace_boundary",
            "type": "hardware_safety",
            "description": "运动不得超出 UR5 工作空间",
            "applies_to": ["plan_grasp", "execute_grasp", "verify_grasp"],
            "check": {"method": "telemetry", "expression": "tcp_pose inside workspace_boundaries"},
            "violation_action": "STOP",
            "how_strategy": "SAFETY",
        },
    ],
    engineering_priors=[
        {"id": "grasp_around_center", "type": "control_prior", "description": "优先抓取杯子质心附近", "applies_to": ["plan_grasp"], "source": "cognitive_wiki", "confidence": 0.85},
        {"id": "verify_before_lift", "type": "validation_prior", "description": "夹爪闭合后先确认接触再提起", "applies_to": ["execute_grasp", "verify_grasp"], "source": "rosclaw_policy", "confidence": 0.92},
    ],
    memory_queries=[
        {"id": "similar_grasp_tasks", "query": "UR5 pick cup grasp planning slip", "intent": "retrieve_similar_episode", "top_k": 5},
    ],
    how_triggers=[
        {"id": "missed_grasp", "when": {"metric": "grasp_contact", "condition": "false"}, "query_hint": "missed grasp manipulator contact timing"},
        {"id": "cup_dropped", "when": {"metric": "grasp_stable", "condition": "false"}, "query_hint": "grasp unstable cup dropped manipulator"},
    ],
    auto_experiments=[
        {"id": "gripper_force_sweep", "description": "测试不同夹爪闭合力度", "variables": ["gripper_force"], "values": ["low", "medium"], "safety_gate": True},
    ],
    prohibited_experiments=["disable_workspace_boundary", "grasp_with_excessive_force"],
    cognitive_wiki_terms=["manipulator grasp planning", "UR5 pick and place"],
    cognitive_wiki_cards=[("manipulator_grasp_stability", 0.84)],
    valid_robots=["ur5"],
)
